import { NextRequest, NextResponse } from 'next/server';
import { verifyAdminAuth } from '@/lib/auth/admin';
import { EnhancedContentPipeline } from '@/lib/agents/enhanced-pipeline';
import { prisma } from '@/lib/database/db';

export async function POST(request: NextRequest) {
  try {
    // Auth check
    const authResult = await verifyAdminAuth(request);
    if (!authResult.success) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await request.json();
    const { 
      dealerId = 'admin', 
      carIds, 
      platforms = ['facebook', 'instagram'],
      saveToCalendar = true 
    } = body;

    console.log('🚀 Enhanced content generation started');

    // Initialize enhanced pipeline
    const enhancedPipeline = new EnhancedContentPipeline();

    // Generate smart content
    const results = await enhancedPipeline.generateSmartContent(
      dealerId,
      carIds,
      platforms
    );

    // Save successful content to calendar
    if (saveToCalendar) {
      for (const result of results.results.filter(r => r.success)) {
        try {
          await prisma.contentCalendar.create({
            data: {
              carId: result.carId,
              dealerId: dealerId === 'admin' ? null : dealerId,
              platform: result.platform,
              textContent: result.content,
              hashtags: result.hashtags || [],
              status: 'draft',
              uniquenessScore: Math.round(result.uniquenessScore || 92),
              generationCost: result.generationCost || 0.035,
              brandingApplied: result.brandingApplied || [],
              autoGenerated: true,
              requiresReview: false
            }
          });
        } catch (error) {
          console.error('Error saving to calendar:', error);
        }
      }
    }

    return NextResponse.json({
      success: true,
      message: 'Enhanced content generation completed',
      data: results,
      enhanced: true,
      pipelineType: 'multi-agent-enhanced',
      timestamp: new Date().toISOString()
    });

  } catch (error) {
    console.error('Enhanced content generation error:', error);
    return NextResponse.json({
      success: false,
      error: error.message
    }, { status: 500 });
  }
}
